# Site settings
title: "All things about testing "
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonpatrick.github.io" # the base hostname & protocol for your site
github_username: testless
poster: Hedwig

timezone: Beijing
# Build settings
highlighter: rouge
permalink: /:categories/:title/
gems: [jekyll-paginate]
# markdown: kramdown
markdown: kramdown
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - tables

paginate: 20
